#!/bin/bash

#echo "Content-type: text/html"
#echo
#exec 2>&1

N="$(basename "$0")"
N="$(basename "$N" .cgi)"
export MONO_SHARED_DIR=/tmp/monodat$UID
[ ! -d $MONO_SHARED_DIR ] && mkdir -p $MONO_SHARED_DIR

if [ -f Makefile ]; then
	make -q "$N".exe || echo "<b>WARNING: $N is out of date!</b><p>"
fi

exec mono --debug ./"$N".exe "$@"
#exec strace -s 10240 -o /tmp/xx.$$.out mono --debug ./"$N".exe "$@"

