application: mobwrite3
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  secure: optional
  static_dir: static
- url: /scripts/q.py
  secure: optional
  script: mobwrite_appengine.py
- url: /
  secure: optional
  script: index_redirect.py
